name: Run tests
on:
  push:
    branches: ["main", "ai-sdk-v5"]
  pull_request:
    branches: ["main", "ai-sdk-v5"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache-dependency-path: |
            example/package.json
            package.json
          node-version: "20.x"
          cache: "npm"
      - run: node setup.cjs
      - run: cd playground && npm run build && cd ..
      - run: npx pkg-pr-new publish ./ ./playground
      - run: npm test
      - run: npm run typecheck
      - run: npm run lint
