name: Run tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: |
            example/package.json
            package.json
          node-version: "20.x"
          cache: "npm"
      - run: node setup.cjs
      - run: npm test
      - run: npm run typecheck
      - run: npm run lint
  pkg_pr_new:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: |
            example/package.json
            package.json
          node-version: "20.x"
          cache: "npm"
      - run: node setup.cjs
      - run: npx pkg-pr-new publish ./ ./playground
